### ISSUE TITLE
Incorrect constructor functions for typed arrays

### ISSUE THREAD

**Issue by sockmaster27** [neon-bindings/rfcs#48]
When returning a typed array, like `JsInt16Array` for example, the following JavaScript expression will evaluate to `false`:
```javascript
x instanceof Int16Array
```

Using Jest, this assertion
```js
expect(arr).toBeInstanceOf(Int16Array)
```
fails and reports the following:
```
Expected constructor: Int16Array
Received constructor: Int16Array
```
This makes me suspect that Neon is using a constructor function with an identical name, but different equality identity.

**Comment by kjvalencik** [comment]
@sockmaster27 are you using any transpilers that could be polyfilling or transforming typed arrays?

I am not ables to reproduce with a simple test:

```rust
use neon::prelude::*;

#[neon::main]
fn main(mut cx: ModuleContext) -> NeonResult<()> {
    cx.export_function("array", |mut cx| {
        JsInt16Array::from_slice(&mut cx, &[0, 1, 2, 3])
    })?;

    Ok(())
}
```

```sh
npm install
node -e 'console.log(require(".").array() instanceof Int16Array)'
# true
```

Internally, Neon is calling [`napi_create_typed_array`](https://nodejs.org/api/n-api.html#napi_create_typedarray).

**Comment by sockmaster27** [comment]
It appears to be a [problem with Jest](https://github.com/jestjs/jest/issues/11864).
Sorry for the inconvenience.
